name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: "*"

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.17
        os:
          - ubuntu-latest
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        make tidy-all
    - name: gofmt
      run: |
        go fmt ./...
    - name: build iocli
      run : |
        go build -o io-cli ./iocli
    - name: iocli gen
      run : |
        ./io-cli gen
    - name: Unit Test
      run: |
        go test ./... -cover -p 1